// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package electricity

import (
	"SmartPower/api/electricity"
)

type ControllerV1 struct{}

func NewV1() electricity.IElectricityV1 {
	return &ControllerV1{}
}
