# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
  gen:
    dao:
      - link: "	mssql:sa:qwerQWER114477@tcp(127.0.0.1:1433)/smart_power"
        jsonCase: "CamelLower"
  build:
    name: "main"
    arch: "amd64,arm64,arm"
    system: "darwin,windows,linux"
    packSrc: "resource/public,resource/sql"
    packDst: "internal/packed/build_pack_data.go"
    version: "v1.0.0"
    path: "./bin"
