// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"SmartPower/internal/dao/internal"
)

// internalXfCompaniesDao is internal type for wrapping internal DAO implements.
type internalXfCompaniesDao = *internal.XfCompaniesDao

// xfCompaniesDao is the data access object for table xf_companies.
// You can define custom methods on it to extend its functionality as you wish.
type xfCompaniesDao struct {
	internalXfCompaniesDao
}

var (
	// XfCompanies is globally public accessible object for table xf_companies operations.
	XfCompanies = xfCompaniesDao{
		internal.NewXfCompaniesDao(),
	}
)

// Fill with you ideas below.
