// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"SmartPower/internal/dao/internal"
)

// internalXfCompaniesElectricityDao is internal type for wrapping internal DAO implements.
type internalXfCompaniesElectricityDao = *internal.XfCompaniesElectricityDao

// xfCompaniesElectricityDao is the data access object for table xf_companies_electricity.
// You can define custom methods on it to extend its functionality as you wish.
type xfCompaniesElectricityDao struct {
	internalXfCompaniesElectricityDao
}

var (
	// XfCompaniesElectricity is globally public accessible object for table xf_companies_electricity operations.
	XfCompaniesElectricity = xfCompaniesElectricityDao{
		internal.NewXfCompaniesElectricityDao(),
	}
)

// Fill with you ideas below.
