// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"SmartPower/internal/dao/internal"
)

// internalXfInfoDao is internal type for wrapping internal DAO implements.
type internalXfInfoDao = *internal.XfInfoDao

// xfInfoDao is the data access object for table xf_info.
// You can define custom methods on it to extend its functionality as you wish.
type xfInfoDao struct {
	internalXfInfoDao
}

var (
	// XfInfo is globally public accessible object for table xf_info operations.
	XfInfo = xfInfoDao{
		internal.NewXfInfoDao(),
	}
)

// Fill with you ideas below.
